### ISSUE TITLE
python hello.py return an error

### ISSUE THREAD

**Issue by gabx** [nabetama/slacky#42]
slack-0.1.31 has been installed with pip. Now when running hello.py:
```python
gabx@hortensia ➤➤ python/slacky-0.1.31 % python hello.py
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    from slacky import Slacky
  File "/developement/language/python/slacky-0.1.31/slacky/__init__.py", line 10, in <module>
    from .requests import Requests, HttpForbidden
ImportError: No module named 'slacky.requests'
```

**Comment by ehippy** [comment]
+1 similar 

```
Traceback (most recent call last):
  File "/bbflask/BBflask.py", line 3, in <module>
    from bbgames import db, player, game, slack
  File "/bbflask/bbgames/slack.py", line 6, in <module>
    from slacky import Slacky
  File "/usr/local/lib/python2.7/dist-packages/slacky/__init__.py", line 10, in <module>
    from .requests import Requests, HttpForbidden
ImportError: No module named requests
```

**Comment by nabetama** [comment]
@gabx @ehippy 

Thank you for create issue.

I tried the same configuration you used, I could reproduce it.

This is the cause of the problem.
```sh
nabetama@nabetamac ~/.pyenv/versions/2.7.8/lib/python2.7/site-packages/slacky
% ll                                                                                                                                                                                                 [2.0.0-p594]
total 40
-rw-r--r--  1 nabetama  staff  8233 12 27 12:56 __init__.pyc
-rw-r--r--  1 nabetama  staff  4266 12 27 12:56 __init__.py
```

And I fixed the bug.
https://github.com/nabetama/slacky/commit/9eac4649a63ccf177512e5cf4524858d9cc9a36e

```diff
@@ -35,7 +35,7 @@
 * `website <https://github.com/nabetama/slacky>`_
 
 """
-from setuptools import setup
+from setuptools import setup, find_packages
 
 setup(
     name='slacky',
 @@ -45,7 +45,7 @@
     author='Mao Nabeta',
     author_email='mao.nabeta@gmail.com',
     url='https://github.com/nabetama/slacky',
-    packages=['slacky'],
+    packages=find_packages(),
     include_package_data=True,
     install_requires=['requests', 'six'],
     provides=['slack'],
```

I apologize for the late response. 
Thank you for reading it through.

enjoy!!
